model_name: 'DWT_Unet_D_Swinir_G'
data_path: '/big_data/qi1/ArSSR_Dataset/crops'
batch_size: 1
num_epochs: 20
n_gpus: 4
name_ckp: 'testing-swinir'
D_type: 'dwt_UNet'
G_type: 'SwinIR'
FE_type: 'resnet10'

